server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pfe-service
          uri: lb://pfe-service
          predicates:
            - Path=/api/pfe/**
        - id: chatbot-service
          uri: lb://chatbot-service
          predicates:
            - Path=/api/chatbot/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
