server.port=8080
spring.application.name=gateway
spring.cloud.discovery.client.simple-service-instance.pfe-service.uri=http://pfe-service:8081
spring.cloud.discovery.client.simple-service-instance.chatbot-service.uri=http://chatbot-service:8081
eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
